Book_My_Movie_show/MovieCoreMVC_UI/Controllers/ShowTimingController.cs
using Book_Show_Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace MovieCoreMVC_UI.Controllers
{
    public class ShowTimingController : Controller
    {
        private IConfiguration _configuration;
        public ShowTimingController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<ShowTiming> users = null;

            using (HttpClient client = new HttpClient())
            {
                string endpoint = _configuration["WebApiBaseUrl"] + "ShowTiming/GetShowTiming";
                using (var resonse = await client.GetAsync(endpoint))
                {
                    if (resonse.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await resonse.Content.ReadAsStringAsync();
                        users = JsonConvert.DeserializeObject<IEnumerable<ShowTiming>>(result);
                    }
                }
            }
            return View(users);
        }
        public async Task<IActionResult> ShowTimingEntry(int movieId)
        {
            IEnumerable<Theater> movieresult = null;
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "Theater/GetTheater";
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        movieresult = JsonConvert.DeserializeObject<IEnumerable<Theater>>(result);
                    }

                }
                
            }
            List<SelectListItem> language = new List<SelectListItem>();
            /*{
                *//* foreach (var item in movieresult)
                  {
                      new SelectListItem { Value = item.Location.LocationDesc, Text = item.Name },
                  }*//*
                new SelectListItem{Value="Select",Text="select"},
                new SelectListItem{Value="Tamil",Text="Tamil"},
                new SelectListItem{Value="English",Text="English"},
                new SelectListItem{Value="Kannada",Text="Kannada"},
            };*/

            language.Add(new SelectListItem { Value = "select", Text = "select" });
                  foreach (var item in movieresult)
            {
                language.Add(new SelectListItem { Value= item.TheatreId.ToString(), Text = item.Name+" "+item.Location.LocationDesc });
            }
        
        ViewBag.Theaterlist = language;
            /*   Movie movie = null;
               using (HttpClient client = new HttpClient())
               {

                   string endpoint = _configuration["WebApiBaseUrl"] + "Movie/GetMovieById?MovieId=" + movieId;
                   using (var response = await client.GetAsync(endpoint))
                   {
                       if (response.StatusCode == System.Net.HttpStatusCode.OK)
                       {
                           var result = await response.Content.ReadAsStringAsync();
                           movie = JsonConvert.DeserializeObject<Movie>(result);
                       }

                   }

               }*/
            ShowTiming showTiming = new ShowTiming();
            showTiming.MovieId=movieId;
            return View(showTiming);
        }
        [HttpPost]
        public async Task<IActionResult> ShowTimingEntry(ShowTiming show)
        {
            ViewBag.staus = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent Content = new StringContent(JsonConvert.SerializeObject(show), Encoding.UTF8, "application/json");
                string endpoint = _configuration["WebApiBaseUrl"] + "ShowTiming/AddShowTiming";
                using (var response = await client.PostAsync(endpoint, Content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "ShowTiming Inserted succesfully";
                        /*return RedirectToAction("BookShowEntry", "BookShow");*/
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Error Happened";

                    }
                }
            }

            return View();
        }




        //Edit ShowTiming
        public async Task<IActionResult> EditShowTiming(int ShowTimingId)
        {
            ShowTiming showTiming = null;
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "ShowTiming/GetShowTimingById?MovieId=" + ShowTimingId;
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        showTiming = JsonConvert.DeserializeObject<ShowTiming>(result);
                    }

                }
            }
            return View(showTiming);
        }

        [HttpPost]
        public async Task<IActionResult> EditShowTiming(ShowTiming showTiming)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(showTiming), Encoding.UTF8, "application/json");
                string endpoint = _configuration["WebApiBaseUrl"] + "ShowTiming/UpdateShowTiming";
                using (var response = await client.PutAsync(endpoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Movie details saved succesfully";
                    }
                    else
                    {
                        ViewBag.staus = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }

        //delete movie
        public async Task<IActionResult> DeleteShowTiming(int ShowTimingId)
        {
            ShowTiming showTiming = null;
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "ShowTiming/GetShowTimingById?MovieId=" + ShowTimingId;
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        showTiming = JsonConvert.DeserializeObject<ShowTiming>(result);
                    }

                }
            }
            return View(showTiming);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteShowTiming(ShowTiming showTiming)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "ShowTiming/DeleteShowTiming?movieId=" + showTiming.ShowTimingId;
                using (var response = await client.DeleteAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "ShowTiming delete succesfully";
                    }
                    else
                    {
                        ViewBag.staus = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }

    }
}

Book_My_Movie_show/MovieCoreMVC_UI/Views/ShowTiming/DeleteShowTiming.cshtml
@model Book_Show_Entity.ShowTiming
@{
    ViewData["Title"] = "DeleteShowTiming";
}

<h1>DeleteShowTiming</h1>


<form method="post" enctype="multipart/form-data">
    <h2>Delete Show Timing</h2><hr />
    <div class="form-group">
        <label>Movie Id</label>
        <input type="text" asp-for="ShowTimingId" class="form-control" placeholder="enter a movie name" required />
    </div>
    <hr />
    <input type="submit" value="Delete" class="btn btn-outline-success" />
    <input type="reset" value="Reset" class="btn btn-outline-secondary" />
    <hr />
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">@ViewBag.message</div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">@ViewBag.message</div>
    }
</form>

Book_My_Movie_show/MovieCoreMVC_UI/Views/ShowTiming/EditShowTiming.cshtml
@{
    ViewData["Title"] = "EditShowTiming";
}

@model Book_Show_Entity.ShowTiming


<div>
    <hr />
    <a asp-controller="ShowTiming" asp-action="Index">Show Timing</a>
    <hr />

</div>
<form method="post" enctype="multipart/form-data">
    <h2>Movie Entry</h2><hr />
    <div class="form-group">
        <label>Movie Id</label>
        <input type="text" asp-for="MovieId" class="form-control" placeholder="enter a movie id" required />
    </div>

    <div class="form-group">
        <label>Theater Id</label>
        <input type="text" asp-for="TheatreId" class="form-control" placeholder="enter a Theatre Id" required />
    </div>

    <div class="form-group">
        <label>Show Time</label>
        <input type="datetime-local" asp-for="ShowTime" class="form-control" placeholder="enter a Show Time" required />
    </div>
    <hr />
    <input type="submit" value="Save" class="btn btn-outline-success" />
    <input type="reset" value="Reset" class="btn btn-outline-secondary" />
    <hr />
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">@ViewBag.message</div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">@ViewBag.message</div>
    }
</form>

Book_My_Movie_show/MovieCoreMVC_UI/Views/ShowTiming/Index.cshtml
@model IEnumerable<Book_Show_Entity.ShowTiming>
@{
    ViewData["Title"] = "Index";
}
@*
<div>
    <a asp-controller="ShowTiming" asp-action="ShowTimingEntry">ShowTiming Entry</a>
</div>*@

<div class="row">
    <div class="col-12">
        <center><h3>Show Timing Details</h3></center>
        <hr />
        <table class="table table-light table-bordered table-hover">
            <thead>
                <tr>
                    <th>Show Timing Id</th>
                    <th>Show Timing</th>
                    <th>Theatre Id</th>
                    <th>Movie Id</th>
                   
                </tr>
            </thead>
            <tbody>
                @foreach (var movie in Model)
                {//default put as model it is keyword in MVC
                 //@ we used to refer the csharp code
                 //razer view compiler.it will convert the code to html understand file
                    <tr>
                        <td>@movie.ShowTimingId</td>
                        <td>@movie.ShowTime</td>
                        <td>@movie.TheatreId</td>
                        <td>@movie.Theater.Location.LocationDesc</td>
                        
                        <td><a asp-controller="ShowTiming" asp-action="EditShowTiming" asp-route-ShowTimingId="@movie.ShowTimingId">Edit</a></td>
                        <td><a asp-controller="ShowTiming" asp-action="DeleteShowTiming" asp-route-ShowTimingId="@movie.ShowTimingId">Delete</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Book_My_Movie_show/MovieCoreMVC_UI/Views/ShowTiming/ShowTimingEntry.cshtml
@model Book_Show_Entity.ShowTiming
@{
    Layout = "~/Views/Shared/UserPage.cshtml";
}

@*<div>
    <hr />
    <a asp-controller="ShowTiming" asp-action="Index">Show Timing</a>
    <hr />

</div>*@
<form method="post" enctype="multipart/form-data">
    <h2>Show Timing Entry</h2><hr />
    <div class="form-group">
        <label>Movie Id</label>
        <input type="text" asp-for="MovieId" class="form-control" placeholder="enter a movie id" required />
    </div>

  @*  <div class="form-group">
        <label>Theater Id</label>
        <input type="text" asp-for="TheatreId" class="form-control" placeholder="enter a Theatre Id" required />
    </div>*@
    <div class="form-group">
        <label>Theater List</label>
        <select asp-for="TheatreId" asp-items="@ViewBag.Theaterlist"></select>
    </div>

    <div class="form-group">
        <label>Show Time</label>
        <input type="datetime-local" asp-for="ShowTime" class="form-control" placeholder="enter a Show Time" required />
    </div>
    <hr />
   @* <a asp-controller="BookShow" class="btn btn-outline-secondary"  asp-action="BookShowEntry" asp-route-ShowTimingId="ShowTimingId">Submit</a>*@
    @*<a asp-controller="BookShow" asp-action="BookShowEntry" class="btn btn-danger" asp-route-ShowTimingId="ShowTimingId">Book Show</a>*@
    <input type="submit" value="Save" asp-controller="ShowTiming"  asp-action="ShowTimingEntry" asp-route-ShowTimingId="ShowTimingId" class="btn btn-outline-success" />
    <input type="reset" value="Reset" class="btn btn-outline-secondary" />
    <a asp-controller="BookShow" class="btn btn-outline-secondary" asp-action="BookShowEntry" asp-route-bookshow="ShowTimingId">Next Page</a>
    <hr />
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">@ViewBag.message</div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">@ViewBag.message</div>
    }
</form>