Book_My_Movie_show/MovieCoreMVC_UI/Controllers/BookShowController.cs
using Book_Show_Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace MovieCoreMVC_UI.Controllers
{
    public class BookShowController : Controller
    {
        private IConfiguration _configuration;
        public BookShowController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<BookShow> users = null;

            using (HttpClient client = new HttpClient())
            {
                string endpoint = _configuration["WebApiBaseUrl"] + "BookShow/GetALLBookShow";
                using (var resonse = await client.GetAsync(endpoint))
                {
                    if (resonse.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await resonse.Content.ReadAsStringAsync();
                        users = JsonConvert.DeserializeObject<IEnumerable<BookShow>>(result);
                    }
                }
            }
            return View(users);
        }
        public IActionResult BookShowEntry(int bookshow)
        {
            BookShow bookShow = new BookShow();
            bookShow.ShowTimingId = bookshow;
            
            return View(bookShow);
        }
        [HttpPost]
        public async Task<IActionResult> BookShowEntry(BookShow bookShow)
        {
            bookShow.TicketCost = (bookShow.NoOfTickets * 200);
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(bookShow), Encoding.UTF8, "application/json");
                string endpoint = _configuration["WebApiBaseUrl"]+ "BookShow/AddBookShow";
                using (var response = await client.PostAsync(endpoint,content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Movie details saved succesfully";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }

            return View();
        }



        //Edit BookShow
        public async Task<IActionResult> EditBookShow(int BookShowId)
        {
            BookShow BookShow = null;
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "BookShow/GetBookShowById?MovieId=" + BookShowId;
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        BookShow = JsonConvert.DeserializeObject<BookShow>(result);
                    }

                }
            }
            return View(BookShow);
        }

        [HttpPost]
        public async Task<IActionResult> EditBookShow(BookShow BookShow)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(BookShow), Encoding.UTF8, "application/json");
                string endpoint = _configuration["WebApiBaseUrl"] + "BookShow/UpdateBookShow";
                using (var response = await client.PutAsync(endpoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Movie details saved succesfully";
                    }
                    else
                    {
                        ViewBag.staus = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }

        //delete movie
        public async Task<IActionResult> DeleteBookShow(int BookShowId)
        {
            BookShow movie = null;
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "BookShow/GetBookShowById?MovieId=" + BookShowId;
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        movie = JsonConvert.DeserializeObject<BookShow>(result);
                    }

                }
            }
            return View(movie);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteBookShow(BookShow BookShow)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "BookShow/DeleteBookShow?BookId=" + BookShow.BookShowId;
                using (var response = await client.DeleteAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "BookShow delete succesfully";
                    }
                    else
                    {
                        ViewBag.staus = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }
    }
}

Book_My_Movie_show/MovieCoreMVC_UI/Controllers/MovieController.cs
using Book_Show_Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace MovieCoreMVC_UI.Controllers
{
    public class MovieController : Controller
    {
        private IConfiguration _configuration;
        public MovieController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Movie> movieresult = null;
            using (HttpClient client = new HttpClient())
            {
                
                string endpoint = _configuration["WebApiBaseUrl"] + "Movie/GetMovies";
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result=await response.Content.ReadAsStringAsync();
                        movieresult=JsonConvert.DeserializeObject<IEnumerable<Movie>>(result);
                    }
                  
                }
            }
            return View(movieresult);
        }
        public IActionResult MovieEntry()
        {
            List<SelectListItem> language = new List<SelectListItem>()
            {
                new SelectListItem{Value="Select",Text="select"},
                new SelectListItem{Value="Tamil",Text="Tamil"},
                new SelectListItem{Value="English",Text="English"},
                new SelectListItem{Value="Kannada",Text="Kannada"},
            };
                ViewBag.languagelist = language;
            return View();
        
            
        }
        [HttpPost]
        public async Task<IActionResult> MovieEntry(Movie movie)
        {
            ViewBag.status = "";

            if (Request.Form.Files.Count > 0)
            {
                MemoryStream ms = new MemoryStream();
                Request.Form.Files[0].CopyTo(ms);
                movie.ImgPoster = ms.ToArray();
            }
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(movie), Encoding.UTF8, "application/json");
                string endpoint = _configuration["WebApiBaseUrl"] + "Movie/AddMovie";
                using (var response = await client.PostAsync(endpoint, content)) 
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Movie details saved succesfully";
                    }
                    else{
                        ViewBag.staus = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }


        //Edit Movie
        public async Task<IActionResult> EditMovie(int movieId)
        {
            Movie movie = null;
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "Movie/GetMovieById?MovieId=" + movieId;
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        movie = JsonConvert.DeserializeObject<Movie>(result);
                    }

                }
            }
            return View(movie);
        }

        [HttpPost]
        public async Task<IActionResult> EditMovie(Movie movie)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(movie), Encoding.UTF8, "application/json");
                string endpoint = _configuration["WebApiBaseUrl"] + "Movie/UpdateMovie";
                using (var response = await client.PutAsync(endpoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Movie details saved succesfully";
                    }
                    else
                    {
                        ViewBag.staus = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }

        //delete movie
        public async Task<IActionResult> DeleteMovie(int movieId)
        {
            Movie movie = null;
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "Movie/GetMovieById?MovieId=" + movieId;
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        movie = JsonConvert.DeserializeObject<Movie>(result);
                    }

                }
            }
            return View(movie);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteMovie(Movie movie)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                
                string endpoint = _configuration["WebApiBaseUrl"] + "Movie/DeleteMovie?movieId="+movie.MovieId;
                using (var response = await client.DeleteAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Movie delete saved succesfully";
                    }
                    else
                    {
                        ViewBag.staus = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }



        /*        public IActionResult EditMovie()
                {
                    return View();
                }*/


    }
}

Book_My_Movie_show/MovieCoreMVC_UI/Views/Movie/DeleteMovie.cshtml
@model Book_Show_Entity.Movie
@{
    ViewData["Title"] = "DeleteMovie";
}

<form method="post" enctype="multipart/form-data">
    <h2>Delete Movie</h2><hr />
    <div class="form-group">
        <label>Movie Id</label>
        <input type="text" asp-for="MovieId" class="form-control" placeholder="enter a movie name" required />
    </div>
    <hr />
    <input type="submit" value="Delete" class="btn btn-outline-success" />
    <input type="reset" value="Reset" class="btn btn-outline-secondary" />
    <hr />
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">@ViewBag.message</div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">@ViewBag.message</div>
    }
</form>

Book_My_Movie_show/MovieCoreMVC_UI/Views/Movie/EditMovie.cshtml
@model Book_Show_Entity.Movie
@{
    ViewData["Title"] = "EditMovie";
}

<form method="post" enctype="multipart/form-data">
    <h2>Movie Entry</h2><hr />
    <div class="form-group">
        <label>Movie Name</label>
        <input type="text" asp-for="MovieName" class="form-control" placeholder="enter a movie name" required />
    </div>

    <div class="form-group">
        <label>Movie Type</label>
        <input type="text" asp-for="MovieType" class="form-control" placeholder="enter a movie type" required />
    </div>

    <div class="form-group">
        <label>Movie Desc</label>
        <input type="text"  class="form-control" placeholder="enter a movie Desc" required />
    </div>
    <hr />
    <input type="submit" value="Save" class="btn btn-outline-success" />
    <input type="reset" value="Reset" class="btn btn-outline-secondary" />
    <hr />
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">@ViewBag.message</div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">@ViewBag.message</div>
    }
</form>

Book_My_Movie_show/MovieCoreMVC_UI/Views/Movie/Index.cshtml
@model IEnumerable<Book_Show_Entity.Movie>
@{
    ViewData["Title"] = "Index";
}



@*<div class="row">
    <div class="col-md-4" style="height:100px;">
    <div class=" alert alert-success">Movie</div>
    </div>
    <div class="col-md-4"style="height:100px;background-color:aqua">
        <div class="card">
            <div class="card" style="width: 18rem;">
                <img src="~/download.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
         </div>
    </div>
    <div class="col-md-4"style="height:100px;background-color:red">Movie2</div>

   
</div>*@

<div>
    <hr />
    <a asp-controller="Movie" asp-action="MovieEntry">MovieEntry</a>
    <hr/>

</div>

@*<div class="row">
    @foreach (var item in Model)
   {
        <div class="card col-1">
            </div>
        <div class="card col-3">
            <img src="data:image/JPG;base64,@Convert.ToBase64String(item.ImgPoster)" style="height:350px" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">@item.MovieName</h5>
                <h5 class="card-title">@item.MovieLanguage</h5>
               
                <p class="card-text">@item.MovieDesc.</p>
                <a class="btn-outline-danger btn-block" asp-controller="BookShow" asp-action="BookShowEntry" asp-route-MovieId="@item.MovieId "><span style="color:white">Book Show</span></a>
                <a asp-controller="BookShow" asp-action="BookShowEntry" class="btn btn-danger">Book Show</a>
            </div>
        </div>
       
    }
</div>*@

<div class="row">
    <div class="col-12">
        <center><h3>Movies</h3></center>
        <hr />
        <table class="table table-light table-bordered table-hover">
            <thead>
                <tr>
                    <th>Movie Id</th>
                    <th>Movie Name</th>
                    <th>Movie Type</th>
                    <th>Movie Desc</th>
                    <th>Movie Desc</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var movie in Model)
                {

                    @*string imageBase64Data =
                    Convert.ToBase64String(movie.ImgPoster);
                    string imageDataURL =
                    string.Format("data:image/jpg;base64,{0}",
                    imageBase64Data);*@
                    
                    //default put as model it is keyword in MVC
                 //@ we used to refer the csharp code
                 //razer view compiler.it will convert the code to html understand file
                    <tr>
                        <td>@movie.MovieId</td>
                        <td>@movie.MovieName</td>
                        <td>@movie.MovieType</td>
                        <td>@movie.MovieDesc</td>
                        <td><img style="height:50px;width:50px" src="data:image/JPG;base64,@Convert.ToBase64String(@movie.ImgPoster)" /></td>
                        <td><a asp-controller="Movie" asp-action="EditMovie" asp-route-MovieId="@movie.MovieId">Edit</a></td>
                        <td><a asp-controller="Movie" asp-action="DeleteMovie" asp-route-MovieId="@movie.MovieId">Delete</a></td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Book_My_Movie_show/MovieCoreMVC_UI/Views/Movie/MovieEntry.cshtml
@model Book_Show_Entity.Movie
@{
    ViewData["Title"] = "MovieEntry";
}

<div>
    <hr />
    <a asp-controller="Location" asp-action="Index">Movie</a>
    <hr />

</div>
<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label>Movie Name</label>
        <input type="text" asp-for="MovieName" class="form-control" placeholder="enter a movie name" required/>
    </div>

    <div class="form-group">
        <label>Movie Type</label>
        <input type="text" asp-for="MovieType" class="form-control" placeholder="enter a movie type" required />
    </div>

    <div class="form-group">
        <label>Movie Desc</label>
       <input type="text" asp-for="MovieDesc" class="form-control" placeholder="enter a movie Desc" required />
    </div>
    <div class="form-group">
        <label>Movie Language</label>
        <select asp-for="MovieLanguage" asp-items="@ViewBag.languagelist"></select>
    </div>
    <div class="form-group">
        <label>Movie Poster</label>
        <input type="file" id="poster" name="poster" class="form-control" required />
    </div>
    <hr />
    <input type="submit" value="Save" class="btn btn-outline-success"/>
    <input type="reset" value="Reset" class="btn btn-outline-secondary" />
    <hr/>
    @if(ViewBag.status=="Ok"){
        <div class="alert alert-success">@ViewBag.message</div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">@ViewBag.message</div>
    }
</form>